#
# Copyright 2021-2024 Software Radio Systems Limited
#
# This file is part of srsRAN
#
# srsRAN is free software: you can redistribute it and/or modify
# it under the terms of the GNU Affero General Public License as
# published by the Free Software Foundation, either version 3 of
# the License, or (at your option) any later version.
#
# srsRAN is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
# GNU Affero General Public License for more details.
#
# A copy of the GNU Affero General Public License can be found in
# the LICENSE file in the top-level directory of this distribution
# and at http://www.gnu.org/licenses/.
#

services:
  5gc:
    container_name: open5gs
    image: 24whitedevil/open5gs:latest
    env_file:
      - ${OPEN_5GS_ENV_FILE:-setup/srsRAN_Project/open5gs.env}
    privileged: true
    ports:
      - "9999:9999/tcp"
    # Uncomment port to use the 5gc from outside the docker network
      - "38412:38412/sctp"
      - "2152:2152/udp"
    command: 5gc -c open5gs-5gc.yml
    healthcheck:
      test: [ "CMD-SHELL", "nc -z 127.0.0.20 7777" ]
      interval: 3s
      timeout: 1s
      retries: 60
    networks:
      oran-intel:
        ipv4_address: ${OPEN5GS_IP:-10.53.1.2}

  cu:
    container_name: srscu
    image: 24whitedevil/srsran:latest
    # stdin_open: true # docker run -i
    # tty: true        # docker run -t
    privileged: true
    cap_add:
      - SYS_NICE
      - CAP_SYS_PTRACE
    volumes:
      - /dev/bus/usb/:/dev/bus/usb/
      - /usr/share/uhd/images:/usr/share/uhd/images
      - ./RAN/entrypoint_0.sh:/tmp/entrypoint.sh
      - ./RAN/cu_0.yml:/config/cu.conf
    networks:
      oran-intel:
        ipv4_address: 10.53.1.240
    depends_on:
      5gc:
        condition: service_healthy
    command:  bash -c 'chmod +x /tmp/entrypoint.sh && /tmp/entrypoint.sh && srscu -c /config/cu.conf'


  
  
  du:
    container_name: srsdu
    image: 24whitedevil/srsran:latest
    # stdin_open: true # docker run -i
    # tty: true        # docker run -t
    privileged: true
    cap_add:
      - SYS_NICE
      - CAP_SYS_PTRACE
    volumes:
      - /dev/bus/usb/:/dev/bus/usb/
      - /usr/share/uhd/images:/usr/share/uhd/images
      - ./RAN/du_zmq.conf:/config/du.conf
      - ./RAN/wait_for_cu_starting.sh:/config/wait_for_cu_starting.sh
    networks:
      oran-intel:
        ipv4_address: 10.53.1.250
    depends_on:
      - cu
      - 5gc
    command: bash -c 'srsdu -c /config/du.conf'


  ue:
    container_name: srsue
    # stdin_open: true
    # tty: true
    image: 24whitedevil/srsue:latest
    user: root
    build:
      context: UE
      dockerfile: Dockerfile
      args:
        OS_VERSION: "22.04"
    devices:
      - /dev/net/tun
    cap_add:
      - SYS_NICE
      - SYS_RESOURCE
      - NET_ADMIN
    env_file:
      - .env
    depends_on:
      - 5gc
      - cu
      - du
    volumes:
      - ./UE/ue_zmq.conf:/configs/ue.conf
      - /dev/null:/tmp/ue.log
    environment:
      - LD_LIBRARY_PATH=/srsue_4G/lib/src/phy/rf/
      - PING=${PING}
    networks:
      oran-intel:
        ipv4_address: 10.53.1.251
    command: bash -c '/srsue_4G/srsue/src/srsue /configs/ue.conf'


  metrics-server:
    container_name: metrics_server
    image: srsran/metrics_server
    build:
      context: RAN/srsRAN_Project/docker/metrics_server
    environment:
      - PORT=${METRICS_SERVER_PORT}
      - BUCKET=${DOCKER_INFLUXDB_INIT_BUCKET}
      - TESTBED=default
      - URL=http://${DOCKER_INFLUXDB_INIT_HOST}:${DOCKER_INFLUXDB_INIT_PORT}
      - ORG=${DOCKER_INFLUXDB_INIT_ORG}
      - TOKEN=${DOCKER_INFLUXDB_INIT_ADMIN_TOKEN}
    ports:
      - 55555:${METRICS_SERVER_PORT}/udp
    networks:
      oran-intel:
        ipv4_address: 10.40.1.4 

  influxdb:
    container_name: influxdb
    image: influxdb:${DOCKER_INFLUXDB_VERSION}
    volumes:
      - influxdb-storage:/var/lib/influxdb2:rw
    env_file:
      - .env
    restart: on-failure:10
    # Uncomment port section to access InfluxDB from outside the docker network
    ports:
      - 8086:${DOCKER_INFLUXDB_INIT_PORT}
    networks:
      oran-intel:
        ipv4_address: 10.40.1.5

  grafana:
    container_name: grafana
    image: srsran/grafana
    build:
      context: RAN/srsRAN_Project/docker/grafana
    volumes:
      - grafana-storage:/var/lib/grafana:rw
    env_file:
      - .env
    depends_on:
      - influxdb
      - metrics-server
    ports:
      - 3300:${GRAFANA_PORT}
    networks:
      oran-intel:
        ipv4_address: 10.40.1.6


volumes:
  gnb-storage:
  grafana-storage:
  influxdb-storage:

networks:
  oran-intel:
    external: true
